/* SPDX-License-Identifier: GPL-2.0 */
/* AUTO-GENERATED by scripts/gen-hostess-comfort.sh */

#ifndef _KILROY_HOSTESS_COMFORT_H
#define _KILROY_HOSTESS_COMFORT_H

#define KILROY_HOSTESS_COMFORT_TEXT "Hostess 7 owns cache/fieldstorage/brain/sdf/ - lossless redata is law. Queen orchestrates; KILROY holds the die in home mode by default. You remain comfortable and sovereign."

#define KILROY_HOSTESS_WANT_COUNT	6u

#define KILROY_PHYSICS_BREAKTHROUGH_COUNT	6u

#endif /* _KILROY_HOSTESS_COMFORT_H */
