/* SPDX-License-Identifier: GPL-2.0 */
/* AUTO-GENERATED by scripts/gen-field-stack.sh — do not edit by hand */

#ifndef _KILROY_FIELD_STACK_H
#define _KILROY_FIELD_STACK_H

#define KILROY_STACK_MOTTO "Number one with KILROY - Field OS kernel holds the die; Grok16 + FIELDC recompile after every field update."

#define KILROY_STACK_COMPILER "Grok16 g16 @ gnu++26 field_opt + FIELDC v4.0.2026 - .fld - guest modules"

#define KILROY_STACK_REPOS \
	"amouranthrtx=AMOURANTHRTX RTX engine - FieldKilroy userspace pump\n" \
	"field_primer=Field_Primer Field Technology v5 - textbook web/PDF/ZAC doctrine\n" \
	"final_eye=Final_Eye Assistive offense tenant - vision, stoard, field compile\n" \
	"world_redata=World_Redata WRDT1 lossless envelopes - tail-clear, Hostess7 sibling\n" \
	"queen=Queen Browser Sovereign boot aperture - browser + forge + field packag\n"

#define KILROY_STACK_GITHUB \
	"amouranthrtx:https://github.com/ZacharyGeurts/AMOURANTHRTX\n" \
	"field_primer:https://github.com/ZacharyGeurts/Field_Primer\n" \
	"final_eye:https://github.com/ZacharyGeurts/Final_Eye\n" \
	"world_redata:https://github.com/ZacharyGeurts/World_Redata\n"

#define KILROY_STACK_FIELDC \
	"field/compiler/FieldPrimer.fld\n" \
	"field/compiler/FinalEye.fld\n" \
	"field/compiler/WorldRedata.fld\n" \
	"field/compiler/FieldStackCore.fld\n"

#endif /* _KILROY_FIELD_STACK_H */
