# SPDX-License-Identifier: GPL-2.0
# KILROY Field Die — kernel/rtx

obj-$(CONFIG_RTX_FIELD_DIE) += rtx_core.o rtx_thermo.o rtx_proc.o \
			       rtx_slots.o rtx_security.o rtx_fcc.o \
			       rtx_hw_field.o kilroy_identity.o kilroy_boot.o \
			       kilroy_field_stack.o kilroy_sdf_field.o
obj-$(CONFIG_RTX_FIELD_NEXUS_GUARD) += kilroy_nexus_guard.o
obj-$(CONFIG_RTX_FIELD_AI_KERNEL) += kilroy_ai_field.o
obj-$(CONFIG_RTX_FIELD_PHYSICS_BREAKTHROUGH) += kilroy_physics_field.o
obj-$(CONFIG_RTX_FIELD_HOSTESS_COMFORT) += kilroy_comfort_field.o
obj-$(CONFIG_RTX_FIELD_POWER) += rtx_power.o
obj-$(CONFIG_RTX_FIELD_FLOW_SLOT) += kilroy_flow.o
obj-$(CONFIG_RTX_FIELD_THERMO_IDLE_CREDIT) += kilroy_thermo_idle.o
obj-$(CONFIG_RTX_FIELD_CACHE_SLOT) += kilroy_cache_field.o
obj-$(CONFIG_RTX_FIELD_DIRECT_SLOT) += kilroy_direct_field.o
obj-$(CONFIG_RTX_FIELD_CHARDEV) += kilroy_chardev.o
obj-$(CONFIG_RTX_FIELD_DRM_FCC) += kilroy_drm_field.o