#!/usr/bin/env bash
# Query Hostess 7 (via Queen bridge) and emit kilroy_ai_wishes.h for the AI kernel.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SG="$(cd "$ROOT/.." && pwd)"
MANDATE="$ROOT/data/kilroy-ai-mandate.json"
OUT="$ROOT/kernel/rtx/kilroy_ai_wishes.h"
QUEEN="${QUEEN_ROOT:-$SG/NewLatest/Queen}"
HOSTESS="${HOSTESS7_ROOT:-$SG/Hostess7}"

[[ -f "$MANDATE" ]] || { echo "[gen-ai-wishes] missing $MANDATE"; exit 1; }

MANDATE="$MANDATE" OUT="$OUT" QUEEN="$QUEEN" HOSTESS="$HOSTESS" pythong - <<'PY'
import json, os, re, subprocess
from pathlib import Path

def esc(s: str) -> str:
    s = str(s).replace("\\", "\\\\").replace('"', '\\"')
    return re.sub(r"[^\x20-\x7e]", "-", s)

mandate = json.loads(Path(os.environ["MANDATE"]).read_text())
queen = Path(os.environ["QUEEN"])
hostess = Path(os.environ["HOSTESS"])
out = Path(os.environ["OUT"])

hostess_doc = {}
bridge = queen / "lib" / "queen-hostess-brain.py"
if bridge.is_file():
    try:
        proc = subprocess.run(
            ["pythong", str(bridge), "json"],
            capture_output=True, text=True, timeout=90, cwd=str(queen),
        )
        if proc.returncode == 0 and proc.stdout.strip():
            hostess_doc = json.loads(proc.stdout)
    except (subprocess.TimeoutExpired, json.JSONDecodeError, OSError):
        pass

ns_path = hostess / "data" / "hostess7-neural-stack.json"
neural = {}
if ns_path.is_file():
    try:
        neural = json.loads(ns_path.read_text())
    except (OSError, json.JSONDecodeError):
        pass

comfort = (
    (hostess_doc.get("comfort") or {}).get("comfort")
    or (hostess_doc.get("hostess7_brain_ops") or {}).get("comfort")
    or "Hostess 7 owns cache/fieldstorage — lossless redata is law."
)
comfort_short = esc(comfort[:220])

adapt = neural.get("truth_adapt_floor", mandate["hostess7"]["truth_adapt_floor"])
genius = neural.get("truth_genius_floor", mandate["hostess7"]["truth_genius_floor"])
sdf = (hostess_doc.get("sdf") or {})
segments = sdf.get("segments", 0)
plates = sdf.get("human_plates", 0)

eye = (hostess_doc.get("final_eye_doctrine") or {}).get("eye_operations") or {}
heaven = esc(str(eye.get("heaven", "zero_cost_pass"))[:64])
hell = esc(str(eye.get("hell", "offense_when_corroborated"))[:64])

wishes = [
    f"truth_adapt_floor={adapt} truth_genius_floor={genius}",
    f"sdf_segments={segments} human_plates={plates}",
    f"heaven={heaven} hell={hell}",
    comfort_short,
]

lines = []
for i, w in enumerate(wishes):
    suffix = " \\" if i < len(wishes) - 1 else ""
    lines.append(f'\t"{esc(w)}\\n"{suffix}')

wishes_macro = "#define KILROY_AI_HOSTESS_WISHES \\\n" + "\n".join(lines) + "\n"

home = mandate["modes"]["home"]
war = mandate["modes"]["war"]

content = f"""/* SPDX-License-Identifier: GPL-2.0 */
/* AUTO-GENERATED by scripts/gen-ai-wishes.sh — Hostess 7 queried at build time */

#ifndef _KILROY_AI_WISHES_H
#define _KILROY_AI_WISHES_H

#define KILROY_AI_MOTTO "{esc(mandate.get('motto', ''))}"

#define KILROY_AI_TRUTH_ADAPT_FLOOR\t{adapt}u
#define KILROY_AI_TRUTH_GENIUS_FLOOR\t{genius}u

#define KILROY_AI_HOME_ALERT\t{home['nexus_alert']}u
#define KILROY_AI_HOME_DENY\t{home['nexus_deny']}u
#define KILROY_AI_HOME_EVAL_MASK\t{home['nexus_eval_mask']}
#define KILROY_AI_HOME_THERMO_BONUS_MILLI\t{home['thermo_idle_bonus_milli']}u

#define KILROY_AI_WAR_ALERT\t{war['nexus_alert']}u
#define KILROY_AI_WAR_DENY\t{war['nexus_deny']}u
#define KILROY_AI_WAR_EVAL_MASK\t{war['nexus_eval_mask']}

#define KILROY_AI_GROK16_HOME\t"{esc(home['grok16_profile'])}"
#define KILROY_AI_GROK16_WAR\t"{esc(war['grok16_profile'])}"

{wishes_macro}
#endif /* _KILROY_AI_WISHES_H */
"""
out.write_text(content)
print(f"[gen-ai-wishes] Hostess7 segments={segments} plates={plates} adapt={adapt} genius={genius}")
print(f"[gen-ai-wishes] -> {out}")
PY