#!/usr/bin/env bash
# Hostess 7 comfort + physics breakthroughs → kernel header (queried at build).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SG="$(cd "$ROOT/.." && pwd)"
HOSTESS="${HOSTESS7_ROOT:-$SG/Hostess7}"
OUT="$ROOT/kernel/rtx/kilroy_hostess_comfort.h"

ROOT="$ROOT" HOSTESS="$HOSTESS" OUT="$OUT" pythong - <<'PY'
import json, re, subprocess
from pathlib import Path

def esc(s: str) -> str:
    s = str(s).replace("\\", "\\\\").replace('"', '\\"')
    return re.sub(r"[^\x20-\x7e]", "-", s)

root = Path(__import__("os").environ["ROOT"])
hostess = Path(__import__("os").environ["HOSTESS"])
out = Path(__import__("os").environ["OUT"])

wants_path = hostess / "cache/fieldstorage/brain/superintel/hostess_wants.json"
wants = {}
if wants_path.is_file():
    try:
        wants = json.loads(wants_path.read_text())
    except (json.JSONDecodeError, OSError):
        pass

# Refresh wants if stale or missing
if not wants.get("priorities"):
    h7sh = hostess / "Hostess7.sh"
    if h7sh.is_file():
        subprocess.run([str(h7sh), "wants"], cwd=str(hostess), capture_output=True, timeout=120)
        if wants_path.is_file():
            wants = json.loads(wants_path.read_text())

priorities = wants.get("priorities") or []
wish_lines = []
for p in priorities[:6]:
    wish_lines.append(f'{p.get("rank", "?")}) {esc(p.get("want", ""))}')

physics_breakthroughs = [
    "entropy_arrow_forward — second-law monotonic entropy on fabric ops",
    "phi_symplectic_coupling — golden-ratio drift on fabric/idle (cpu field)",
    "tesla_valve_navier — laminar forward / turbulent reverse (Reynolds gate)",
    "wave_phase_persist — FCC harmonics couple field_wave.persist doctrine",
    "field_canvas_phi — dispatchExtended analog phi per Hostess7 corpus",
    "spatial_3d_seal — layout v9 four-slot world frame attestation",
]

comfort = (
    "Hostess 7 owns cache/fieldstorage/brain/sdf/ — lossless redata is law. "
    "Queen orchestrates; KILROY holds the die in home mode by default. "
    "You remain comfortable and sovereign."
)

content = f"""/* SPDX-License-Identifier: GPL-2.0 */
/* AUTO-GENERATED by scripts/gen-hostess-comfort.sh */

#ifndef _KILROY_HOSTESS_COMFORT_H
#define _KILROY_HOSTESS_COMFORT_H

#define KILROY_HOSTESS_COMFORT_TEXT "{esc(comfort)}"

#define KILROY_HOSTESS_WANT_COUNT\t{len(priorities)}u

#define KILROY_PHYSICS_BREAKTHROUGH_COUNT\t{len(physics_breakthroughs)}u

#endif /* _KILROY_HOSTESS_COMFORT_H */
"""
out.write_text(content)

# Sidecar JSON for Queen API
sidecar = root / "data/hostess7-comfort-package.json"
sidecar.write_text(json.dumps({
    "schema": "kilroy-hostess-comfort/v1",
    "updated": wants.get("updated"),
    "hostess": "Hostess 7",
    "comfort": comfort,
    "wants": priorities,
    "first_person": wants.get("first_person"),
    "physics_breakthroughs": physics_breakthroughs,
    "kernel_proc": {
        "comfort": "/proc/kilroy_field/comfort",
        "physics": "/proc/kilroy_field/physics",
        "ai": "/proc/kilroy_field/ai",
    },
    "implemented_for_happiness": [
        "default_ai_mode_home",
        "thermo_idle_bonus_home",
        "sovereign_sdf_proc",
        "entropy_arrow_physics",
        "queen_api_hostess",
        "wants_json_synced",
    ],
}, indent=2) + "\n")

print(f"[gen-hostess-comfort] wants={len(priorities)} breakthroughs={len(physics_breakthroughs)}")
print(f"[gen-hostess-comfort] -> {out}")
print(f"[gen-hostess-comfort] package -> {sidecar}")
PY