#!/usr/bin/env bash
# Regenerate kernel/rtx/kilroy_field_stack.h from data/field-stack-mandate.json
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANDATE="$ROOT/data/field-stack-mandate.json"
OUT="$ROOT/kernel/rtx/kilroy_field_stack.h"

[[ -f "$MANDATE" ]] || { echo "[gen-field-stack] missing $MANDATE"; exit 1; }

MANDATE="$MANDATE" OUT="$OUT" pythong - <<'PY'
import json, os, re
from pathlib import Path

def esc_c(s: str) -> str:
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    s = re.sub(r"[^\x20-\x7e]", "-", s)  # ASCII-safe for kernel build
    return s

def macro_lines(name: str, lines: list[str]) -> str:
    if not lines:
        return f"#define {name} \"\"\n"
    parts = [f"#define {name} \\"]
    for i, line in enumerate(lines):
        suffix = " \\" if i < len(lines) - 1 else ""
        parts.append(f'\t"{esc_c(line)}\\n"{suffix}')
    return "\n".join(parts) + "\n"

mandate = json.loads(Path(os.environ["MANDATE"]).read_text())
out = Path(os.environ["OUT"])
motto = esc_c(mandate.get("motto", "KILROY field stack"))
doc = mandate.get("doctrine") or {}
compiler = esc_c(f"{doc.get('compiler_primary','Grok16')} + {doc.get('compiler_runtime','FIELDC')}")

repo_lines = []
gh_lines = []
for r in mandate.get("repos") or []:
    if r.get("id") == "kilroy":
        continue
    repo_lines.append(f'{r["id"]}={r.get("name", r["id"])} {r.get("role","")[:56]}')
    if r.get("github"):
        gh_lines.append(f'{r["id"]}:{r["github"]}')

fld_lines = []
for t in mandate.get("fieldc_targets") or []:
    fld = t.get("fld", "")
    if fld.startswith("field/compiler/"):
        fld_lines.append(fld)

content = f"""/* SPDX-License-Identifier: GPL-2.0 */
/* AUTO-GENERATED by scripts/gen-field-stack.sh — do not edit by hand */

#ifndef _KILROY_FIELD_STACK_H
#define _KILROY_FIELD_STACK_H

#define KILROY_STACK_MOTTO "{motto}"

#define KILROY_STACK_COMPILER "{compiler}"

{macro_lines("KILROY_STACK_REPOS", repo_lines)}
{macro_lines("KILROY_STACK_GITHUB", gh_lines)}
{macro_lines("KILROY_STACK_FIELDC", fld_lines)}
#endif /* _KILROY_FIELD_STACK_H */
"""
out.write_text(content)
print(f"[gen-field-stack] -> {out}")
PY