#!/usr/bin/env bash
# Regenerate FieldKilroySyscalls.hpp from compat substrate unistd.h
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=kilroy-compat-path.sh
source "$ROOT/scripts/kilroy-compat-path.sh"
UNISTD="$KILROY_COMPAT_SRC/arch/x86/include/generated/uapi/asm/unistd_64.h"
OUT="${1:-$ROOT/userspace/field-kilroy/FieldKilroySyscalls.hpp}"

[[ -f "$UNISTD" ]] || UNISTD="$KILROY_COMPAT_SRC/include/uapi/asm-generic/unistd.h"
[[ -f "$UNISTD" ]] || { echo "[gen-syscalls] missing unistd headers"; exit 1; }

pythong - "$UNISTD" "$OUT" <<'PY'
import re, sys
from pathlib import Path

src, out = Path(sys.argv[1]), Path(sys.argv[2])
text = src.read_text()
pairs = []
for m in re.finditer(r'^#define __NR_(\w+)\s+(\d+)', text, re.M):
    pairs.append((m.group(2), m.group(1)))
pairs.sort(key=lambda x: int(x[0]))
seen = set()
lines = []
for nr, name in pairs:
    if name in seen:
        continue
    seen.add(name)
    lines.append(f"    {name} = {nr},")

out.write_text("""#pragma once
// Auto-generated by scripts/kilroy-gen-syscalls.sh — do not edit by hand.
#include <cstdint>
namespace FieldKilroy {
constexpr const char* KERNEL_ABI = "kilroy-field-1.0";
constexpr std::uint32_t SYSCALL_COUNT = %d;
enum class Nr : std::int64_t {
%s
};
} // namespace FieldKilroy
""" % (len(lines), "\n".join(lines)))
print(f"[gen-syscalls] {len(lines)} syscalls -> {out}")
PY